### ISSUE TITLE
Add count to filters

### ISSUE THREAD

**Issue by bryceerobertson** [StampyAI/AISafety.com#151]
Similar to this 

<img width="187" alt="Image" src="https://github.com/user-attachments/assets/070e8996-50f6-45a3-88b9-b9fe5e8b00b4" />

**Comment by bryceerobertson** [comment]
@RainZoneO2 some context around filters: they are powered (to the best of my understanding) by 1) site-wide custom code:

<img width="1405" alt="Image" src="https://github.com/user-attachments/assets/b78008cd-8987-4268-a5d8-1ec03b18abbb" />

2) custom code in an embed at the bottom of each individual page:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/81f2635c-5ad6-4723-b104-04b4e07a4b9c" />

3) custom attributes in the collection lists:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/1a41b421-1c6b-42db-941d-d4b88b0d6606" />

**Comment by bryceerobertson** [comment]
Just a heads up I've published the site to main domain in order to publish other stuff – I don't think it's a problem since the current state of the filter counts is already decent

**Comment by RainZoneO2** [comment]
I made some more progress on adding this to all the pages that need a filter count. 
Working on Jobs page right now but having some trouble with some of the filters because the names are slightly different than the data, not hard to fix just tedious.
And the issue about dynamic count not working still exists, still working on fixing that.

**Comment by bryceerobertson** [comment]
@RainZoneO2 would you be up for adding this to the rest of the resource pages? i.e. /stay-informed, /map, and /jobs.

I understand making them dynamic is roadblocked by needing advice from @soerenelverlin? But it's alreday valuable enough without dynamic to warrant adding to all resources I think (+ consistency across the resources is important)

**Comment by RainZoneO2** [comment]
@bryceerobertson Yep would be up for it. Apologies on dropping this, was pretty busy with some other stuff!

In that case, I'll just focus on getting static counts up and later work on the dynamic thing as an extra

**Comment by bryceerobertson** [comment]
Sounds good, thanks!

**Comment by bryceerobertson** [comment]
Hey @RainZoneO2, would you be able to give us a date you'll be able to do this by?

**Comment by RainZoneO2** [comment]
@bryceerobertson Hey yeah, I'll finish this today. I just got back from a family trip to Toronto yesterday so I wasn't able to work on it

**Comment by bryceerobertson** [comment]
Nice one, thanks. Please close this issue when done so I know

**Comment by bryceerobertson** [comment]
To do: make behaviour such that ticking a filter doesn't make the other tickboxes within the same filter go to 0. Ticking it should only affect the numbers for the other filters.
